"""initial tables

Revision ID: 4b84609a1b45
Revises: 
Create Date: 2026-02-18 12:05:23.788840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b84609a1b45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    op.drop_table('invoice')
    op.drop_table('app_user')
    op.drop_table('contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.CheckConstraint("contact_type::text = ANY (ARRAY['PERSONAL'::character varying, 'BUSINESS'::character varying, 'FREELANCE'::character varying]::text[])", name='contact_contact_type_check'),
    sa.CheckConstraint("preferred_language::text = ANY (ARRAY['ENGLISH'::character varying, 'DUTCH'::character varying, 'HEBREW'::character varying, 'FRENCH'::character varying, 'GERMAN'::character varying, 'SPANISH'::character varying]::text[])", name='contact_preferred_language_check'),
    sa.PrimaryKeyConstraint('id', name='contact_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('app_user',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.CheckConstraint("role::text = ANY (ARRAY['ADMIN'::character varying, 'USER'::character varying]::text[])", name='app_user_role_check'),
    sa.PrimaryKeyConstraint('id', name='app_user_pkey')
    )
    op.create_table('invoice',
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('outsideeu', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('units', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payment_instructions', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.CheckConstraint("currency::text = ANY (ARRAY['EUR'::character varying, 'USD'::character varying, 'GBP'::character varying, 'CHF'::character varying, 'JPY'::character varying]::text[])", name='invoice_currency_check'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], name='fkmgjclr5amslh6f6tsi5iigt3t'),
    sa.PrimaryKeyConstraint('id', name='invoice_pkey')
    )
    op.create_table('client',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='client_pkey')
    )
    # ### end Alembic commands ###
